# Generated by Django 4.1.13 on 2024-05-17 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0017_alter_folders_publish_alter_word_ne_lan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 12, 33, 23, 367949, tzinfo=datetime.timezone.utc)),
        ),
    ]
